name: ssh-logging workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

       # log in to docker
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       # i build the image
      - name: Build the image
        run: docker build -t  mazivazvose/ssh-logging:latest -t mazivazvose/ssh-logging:${{ github.sha }} .

       # i want to confirm if the image was built
      - name: Show images
        run: docker images

        # after confirming then i want the images to docker hub
      - name: Push images to docker
        run: |
          docker push mazivazvose/ssh-logging:latest
          docker push mazivazvose/ssh-logging:${{ github.sha }}
